const router = require('express').Router()
const AuthController = require('../../controllers/auth/index')
const Validator = require('../../validations/auth')
router.post('/login',Validator.Login, AuthController.login.Post)
router.post('/register', Validator.Register,AuthController.register.Post)
router.get('/verify',AuthController.register.VerifyCode)
router.post("/forgot",AuthController.forgot.Forgot)
router.post('/reset-check',AuthController.forgot.ResetCheck)
router.post('/reset',AuthController.forgot.ResetChange)
module.exports = router